# Generated by Django 5.1.4 on 2025-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.JSONField(),
        ),
    ]
