# Generated by Django 5.1.4 on 2025-01-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Shipping", "Shipping"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                    ("Delivered", "Delivered"),
                ],
                default="Shipping",
                max_length=10,
            ),
        ),
    ]
