# Generated by Django 5.1.4 on 2025-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_products_products_pr_categor_58ea33_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Image",
            field=models.ImageField(upload_to="products/images/"),
        ),
    ]
