# Generated by Django 5.1.4 on 2025-01-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Image",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
    ]
